[package]
name = "sp"
version = "0.1.0"
authors = ["tataRinaz <44062002+tataRinaz@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

nom = "5.0.1"
rustyline = "5.0.4"